name: Test CI

on:
  push:
    branches: [ module, master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14-alpine

    steps:
    - name: Install Puppeteer deps
      run: apt-get update && apt-get install -y libgbm-dev

    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Yarn Install
      run: yarn install --frozen-lockfile

    - name: ESLint Check
      run: yarn lint

    - name: Jest
      run: yarn test:ci

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage-final.json