name: Test CI

on:
  push:
    branches: [ module, master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:15

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      nodejs service:
        # Docker Hub image
        image: node:15
        ports:
          - 5900:5900

    steps:

    - name: Yarn Install
      run: yarn

    - name: ESLint Check
      run: yarn lint

    - name: Jest
      run: yarn test:ci

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage-final.json